### ISSUE TITLE
Getting an exception when trying the tool for my id 99

### ISSUE THREAD

**Issue by waelabboud** [mhashem/attendance-app#1]
**shell:>attendance 99**
2019-02-06 09:21:29.925  INFO 20068 --- [           main] c.m.a.c.impl.AttendanceMachineClient     : Status Code 200
2019-02-06 09:21:29.925 ERROR 20068 --- [           main] c.m.a.shell.AttendanceComponent          : Text 'Working Time Setup Error' could not be parsed at index 0

java.time.format.DateTimeParseException: Text 'Working Time Setup Error' could not be parsed at index 0
        at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949) ~[na:1.8.0_201]
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_201]
        at java.time.LocalTime.parse(LocalTime.java:441) ~[na:1.8.0_201]
        at java.time.LocalTime.parse(LocalTime.java:426) ~[na:1.8.0_201]
        at com.mhachem.attendance.utils.Helper.parseTime(Helper.java:37) ~[classes!/:0.0.4-SNAPSHOT]
        at com.mhachem.attendance.utils.Helper.parseDay(Helper.java:25) ~[classes!/:0.0.4-SNAPSHOT]

**Comment by mhashem** [comment]
I value your notice, please open a Pull request for the fix you showed me 😄 thanks in advance @waelabboud
